### PR TITLE
Add support for (C)Python >= 3.7

### PR DESCRIPTION
**Pull request by ClasherKasten**
**This PR provides support for (C)Python versions 3.7, 3.8 and 3.9 for this library**

I'll open this as a draft, cause I think this is not even close to being finished.

Because of the missing test coverage, I couldn't validate if this code really fixes the problem. so there are two ways:
- adding test coverage (I would suggest this option)
- looking through the documentation of python and looking for changes that could be an issue for supporting lower versions

also I think the code quality of this draft is not the best, 

If anything should be changed, please propose it, I don't want this branch to be a complete mess, so I disabled edits from maintainers.

i will try to answer question as fast as possible.

### CODE REVIEW

**Comment by AnnaSasDev** [comment]
I like the enthusiasm, thanks!
One small note, the `from __future__ import annotations` is technically not viable anymore, see: [https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/](https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/)

**Comment by ClasherKasten** [comment]
I can't see why `from __future__ import annotations` is not technically viable anymore.

The feature is still in the last Python version `3.11.0b5`
look at the implementation of [__future__.py](https://github.com/python/cpython/blob/main/Lib/__future__.py)
```py
annotations = _Feature((3, 7, 0, "beta", 1),
                       None,
                       CO_FUTURE_ANNOTATIONS)
```

The Text in the Mail also says
> As such, at this time, the only reasonable path forward that the SC sees is to defer the decision in Python 3.11 again, essentially keeping the 3.10 status quo.
Seems like they just need more time to think about it.

also the **"3.10 status quo"** is the `from __future__ import annotations`

Please correct me if i'm wrong, but the `from __future__ import annotations` is still usable and practical while they discuss how it'll work in the future.

**Comment by AnnaSasDev** [comment]
I must have misread something then, my apologies

**Comment by AnnaSasDev** [comment]
I personally agree with the fact that the library as it currently stands is missing a lot of features like proper test coverage and such.
I have been ill for a large portion of July and am just getting back into the flow of things, so I'll get to this as soon as possible

**Comment by AnnaSasDev** [comment]
Yet, as I am still working on the 1.0.0 I propose we hold off from doing the backwards compatible enhancement as I'm probably going to change things around a fair bit before the 1.0.0 is completed (as I do with all my 0.x.x versions, which are meant as a sort of "pre-release" state of things)

**Comment by ClasherKasten** [comment]
> Yet, as I am still working on the 1.0.0 I propose we hold off from doing the backwards compatible enhancement as I'm probably going to change things around a fair bit before the 1.0.0 is completed (as I do with all my 0.x.x versions, which are meant as a sort of "pre-release" state of things)

That's completely fine. This Draft was mostly made for discussing the changes. After a few considerations i don't think that this project is a good place for the  `_dataclass` code. It'll be more useful to add this to **[AthenaLib](https://github.com/DirectiveAthena/AthenaLib)**. **[AthenaLib](https://github.com/DirectiveAthena/AthenaLib)** is basically a dependency in all of the **DirectiveAthena** projects. So including the `_dataclass` in **AthenaLib** would give all the **DirectiveAthena** projects the ability to get better backward compatibility.

Thus i close this Draft for the following reasons:

- The `_dataclass` will get a new PR in [AthenaLib](https://github.com/DirectiveAthena/AthenaLib)
- The code for the `match` statement can receive breaking changes without merge conflicts in the future.
- The replacement code for the `match` statement gets a new PR after releasing 1.0.0 and hence can be added to the 1.1.0 milestone

**Pull request closed without merging**
