### PR TITLE
Feat: Proper typing

### PR DESCRIPTION
**Pull request by ClasherKasten**
WIP. Proposal, open for discussion.

### CODE REVIEW

**Comment by AnnaSasDev** [comment]
Almost all of the import changes have to be reverted.
It will never be acceptable in these projects to split up every different object from the same module to a different line. 
At a glance, all imports are affected, please refrain from doing so.
This is not a useful addition to the project

**Comment by ClasherKasten** [comment]
> This is not a useful addition to the project

Thought that it would be useful in this chaotic projects, but if you don't think so and don't wanna ever improve your code, it's OK to me and I gonna revert the changes to the import statements.

> It will never be acceptable in these projects to split up every different object from the same module to a different line.

It was never mentioned in the Style-Guide in [RulesAndGuidelines](https://github.com/Athena-Chaos-Driven-Code/RulesAndGuidelines)

But I wanna ask something back. Why do you felt the urge to close this?  It was marked as `Draft` and `WIP`. I could've changed the `import`s and the rest of the changes could also be discussed. Why do I now have to open a new PR?

**Comment by AnnaSasDev** [comment]
Because the entire refactor library is still in an early stage where lots of things might and will change.
Making these kind of additions this early on isn't productive.

Marking the pull request as a draft isn't an excuse for proper course of action. If you think there is an issue with the current typing in the project, make an issue and discus it there before any needless work is put into anything.

In the past I've stated clearly that I try to adhere to pep 8 where logical, like : https://peps.python.org/pep-0008/#imports

Please, don't make future pull requests when a project I'm working on daily is still in development. If you see an issue, create an issue.

**Comment by ClasherKasten** [comment]
> Because the entire refactor library is still in an early stage where lots of things might and will change.
Making these kind of additions this early on isn't productive.

OK, I simply have a different opinion.

> Please, don't make future pull requests when a project I'm working on daily is still in development. If you see an issue, create an issue.

~I'll do that.~ OK, I did. Take a look at #46.

---

> In the past I've stated clearly that I try to adhere to pep 8 where logical, like : https://peps.python.org/pep-0008/#imports

This isn't a thing with [PEP8](https://peps.python.org/pep-0008), but instead with using `git`. Splitting up the imports can help prevent merge conflicts.

---

> Marking the pull request as a draft isn't an excuse for proper course of action. If you think there is an issue with the current typing in the project, make an issue and discus it there before any needless work is put into anything.

Why? Marking it as a Draft clearly states a developing intention and I would've been OK with changing things along the line of the daily development of the project. It's not that you could like... pull remote changes into a local branch and then work with them :+1: (git is a nice tool, at least if you know how to work with it...)

**Pull request closed without merging**
